- name: Deploy app
  hosts: localhost
  tasks:
    - name: update apt
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: check nginx
      service:
        name: nginx
        state: started
        enabled: yes

